### ISSUE TITLE
jdk:openjdk-jre-17 busybox vulnerabilities 

### ISSUE THREAD

**Issue by mswiderski** [chainguard-images/jdk#16]
**Description**

When running java application on jdk:openjdk-jre-17 prisma cloud reports following vulnerabilities for busybox:

- [CVE-2022-30065](https://nvd.nist.gov/vuln/detail/CVE-2022-30065)
- [CVE-2022-28391](https://nvd.nist.gov/vuln/detail/CVE-2022-28391)

I looked into wolfi and it seems [it was already addressed](https://github.com/wolfi-dev/os/commit/00b859ccfb4d23eb5451ff9d355a51f407ae1a6f) though not sure jdk is already based on wolfi.

Either way is there any work planned to address these cves?

**Comment by amouat** [comment]
Thanks for the report @mswiderski .

The current situation is a bit confusing, and I apologise for that. The image you are looking at isn't a Wolfi build, but an Alpine based one. I don't think Alpine have released a fix for busybox yet, so that's why the CVE is there (it should be fixed in a few days).

We are actively working on a new Wolfi build of the openjdk, and the packages are already in Wolfi. We are in the process of moving our images to a single repo to simplify things, and were planning to make the Wolfi image available then. This image should have 0 vulns, be compiled against glibc (not musl) and will also be considerably smaller. If you'd like to try this out before we change repos, please let me know and I'll get you a build.

I'll close this issue for the moment.

**Comment by kaniini** [comment]
Alpine released a fix for both of these CVEs months ago.

**Comment by amouat** [comment]
Thanks @kaniini . In this case I think it's a false positive (the images don't contain a vulnerable version of busybox). I believe the CVE shows up in a Grype scan, and Grype doesn't check the Alpine vulnerability feed for our images.

**Comment by mswiderski** [comment]
thanks a lot for very quick responses. 

@amouat I would be more than happy to try the new image so please let me know where I can get one to take it for a spin.

**Comment by amouat** [comment]
@mswiderski turns out I was wrong. The new Wofli built image has actually already overwritten the old image. So `cgr.dev/chainguard/jdk:openjdk-17` *is* the new Wolfi image.

The reason the CVEs appear is because grype isn't yet reading the wolfi security feed (see https://github.com/wolfi-dev/.github/blob/main/SECURITY.md for details). 

I'll update the README shortly to make this clear.

Please let me know if this is causing you any problems right now.

**Comment by mswiderski** [comment]
@amouat does this also apply to all the taks of `cgr.dev/chainguard/jdk`?

So if I got it right, the images are already based on Wolfi and are not affected by above mentioned CVEs. And it is matter of time that the scanner will be aware of that.

Actually with this image I was able to go down to only 2 of them instead of more than 50 so it's a huge step forward anyway. Though going down to zero and seeing services being perfectly green in the scanner would be a killer :)

**Comment by amouat** [comment]
Yes, exactly. And we want to see that graph green as well :)

BTW if you'd like to talk more I'm adrian@chainguard.dev. I'd be interested to hear what you're using the image for and what you'd like to see.

**Comment by mswiderski** [comment]
looking more it seems the image is based on Wolfi 20220914 - could it be that this version does not have the fixes for busybox?

**Comment by amouat** [comment]
All current images have that version string (I'm still investigating why it's exactly that number).

If you run syft on the image e.g:

```
syft packages cgr.dev/chainguard/jdk:openjdk-17
 ✔ Loaded image
 ✔ Parsed image
 ✔ Cataloged packages      [30 packages]

NAME                    VERSION          TYPE
CodePointIM             17.0.5-internal  java-archive
FileChooserDemo         17.0.5-internal  java-archive
Font2DTest              17.0.5-internal  java-archive
J2Ddemo                 17.0.5-internal  java-archive
Metalworks              17.0.5-internal  java-archive
Notepad                 17.0.5-internal  java-archive
SampleTree              17.0.5-internal  java-archive
Stylepad                17.0.5-internal  java-archive
SwingSet2               17.0.5-internal  java-archive
TableExample            17.0.5-internal  java-archive
TransparentRuler        17.0.5-internal  java-archive
bash                    5.2_rc4-r0       apk
busybox                 1.35.0-r3        apk
bzip2                   1.0.8-r2         apk
ca-certificates-bundle  20220614-r2      apk
expat                   2.5.0-r0         apk
fontconfig              2.14.0-r1        apk
freetype                2.12.1-r0        apk
glibc                   2.36-r3          apk
glibc-locale-en         2.36-r3          apk
glibc-locale-posix      2.36-r3          apk
jrt-fs                  17.0.5-internal  java-archive
libbrotlicommon1        1.0.9-r0         apk
libbrotlidec1           1.0.9-r0         apk
libpng                  1.6.38-r0        apk
ncurses                 6.3-r2           apk
ncurses-terminfo-base   6.3-r2           apk
openjdk-17              17.0.5.8-r1      apk
wolfi-baselayout        20221104-r0      apk
zlib                    1.2.13-r1        apk
```

We can see the exact version of busybox is `1.35.0-r3`. If we then cross-reference against our security database at https://packages.wolfi.dev/os/security.json you can find:

```
...
"pkg": {
        "name": "busybox",
        "secfixes": {
          "1.35.0-r3": [
            "CVE-2022-28391",
            "CVE-2022-30065"
          ]
        }
      }
    },
...
```

Indicating that we have addressed the CVEs in this version. The YAML used to build the package can be found at https://github.com/wolfi-dev/os/blob/main/busybox.yaml

**Comment by mswiderski** [comment]
thanks for confirmation @amouat and hint about `syft` tool.
